# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alex Manusu
tagline:          'A blog based on <a href="https://github.com/poole/hyde">Hyde</a>'
description:      'The journal of Alex Manusu'
url:              http://hyde.getpoole.com

author:
  name:           'Alex Manusu'
  url:            https://twitter.com/alexvision

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde